### ISSUE TITLE
broken build

### ISSUE THREAD

**Issue by nimbusgb** [gkonovalov/android-vad#10]
activateRecordingButtonWithPermissionCheck() line 108 of mainactivity.kt has no function definition?

two others but thats the one thats got me!

**Comment by gkonovalov** [comment]
You will need to build or rebuild the project so that PermissionsDispatcher can generate `activateRecordingButtonWithPermissionCheck()` for you.

**Comment by gkonovalov** [comment]
For more details please see: [https://github.com/permissions-dispatcher/PermissionsDispatcher/](https://github.com/permissions-dispatcher/PermissionsDispatcher/)
