### ISSUE TITLE
Issues with WebRTC VAD Library Integration

### ISSUE THREAD

**Issue by drone0898** [gkonovalov/android-vad#13]
Hello,

I've been trying to use the WebRTC VAD library in my project, but I've encountered issue:

1. When I add implementation 'com.github.gkonovalov.android-vad:webrtc:2.0.3' to my app's Gradle file, I get the following error: Failed to resolve: com.github.gkonovalov.android-vad:webrtc:2.0.3. This happens even though I have registered maven 'https://jitpack.io/' repositories.

Thank you for providing this great library! I would appreciate any help in resolving these issues.

Android Studio Version : Android Studio Flamingo | 2022.2.1 Patch 2
Kotlin Version : 1.8.10 * JAVA_17
Gradle Version : 8.0

**Comment by jay-devx** [comment]
**Do this in build.gradle (Module)**
```
implementation 'com.github.gkonovalov.android-vad:webrtc:2.0.3'
implementation 'com.github.gkonovalov.android-vad:silero:2.0.3'
implementation 'com.microsoft.onnxruntime:onnxruntime-android:1.15.0'

```
**Do this in Settings.gradle**
```
pluginManagement {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
}
```

**Comment by drone0898** [comment]
settings.gradle
maven { url 'https://jitpack.io' } code works for me
thanks for your help.
