### ISSUE TITLE
VAD Short array usage problem while recording from Mic on Android phones.

### ISSUE THREAD

**Issue by jay-devx** [gkonovalov/android-vad#14]
Thanks for the great library! I used VAD with android and it works well, but I am running into another issue. The VAD detection code needs a short array of audio data from Mic and once detected I pass this to another library for processing which expects audio data as byte array. I tried converting audio data from short array to byte array but it kept failing. The other issue is a performance overhead for conversion. Can VAD work with byte array, although I know short array keep better audio quality. If not, then what is a recommended approach to convert mic audio data from Short array to byte array?

Related references - 
https://stackoverflow.com/questions/15124050/audiotrack-short-array-to-byte-array-distortion-using-jlayerjava-mp3-decoder
https://stackoverflow.com/questions/24666961/converting-short-array-from-audio-record-to-byte-array-without-degrading-audio-q
https://stackoverflow.com/questions/51278201/android-audiotrack-playback-short-array-16bit

**Comment by gkonovalov** [comment]
Hi @jay-devx,

Currently, the models support the following input parameters:

_WebRTC VAD: short array,
SIlero: float array,
Yamnet: float array._

You will likely need to record audio as a byte array and manually convert it to one of these audio data types. This process will create overhead, but it is currently the only available option.

I am planning to add support of different data type later, for now you can convert it from your side, please see examples below:

Buffer size for ByteArray should be 2x bigger than the Frame size:

` private inner class ProcessVoice : Runnable {
        override fun run() {
            Process.setThreadPriority(Process.THREAD_PRIORITY_AUDIO)
            val size = frameSize * 2

            while (!Thread.interrupted() && isListening) {
                val buffer = ByteArray(size)
                audioRecord?.read(buffer, 0, buffer.size)
                callback.onAudio(buffer)
            }
        }
    }`

`  override fun onAudio(audioData: ByteArray) {
        vad.setContinuousSpeechListener(audioData.toShortSamples(), object : VadListener {
            override fun onSpeechDetected() {
                requireActivity().runOnUiThread { speechTextView.setText(R.string.speech_detected) }
            }

            override fun onNoiseDetected() {
                requireActivity().runOnUiThread { speechTextView.setText(R.string.noise_detected) }
            }
        })
    }

    inline fun ByteArray.mapPairsToDoubles(block: (Byte, Byte) -> Short)
            = ShortArray(size / 2){ i -> block(this[2 * i], this[2 * i + 1]) }
            
    fun ByteArray.toShortSamples() = mapPairsToDoubles{ a, b ->
        (a.toInt() and 0xFF or (b.toInt() shl 8)).toShort()
    }
`

**Comment by jay-devx** [comment]
Hi @gkonovalov,

Thanks for the answer. I tried reading a byte array from Mic stream and then converted it into a short array using your function and it seem to work well. It correctly detects silence and speech. Really appreciate your time and support on the library. Cheers!

**Comment by jay-devx** [comment]
Closing the issue based on solution provided.
