### ISSUE TITLE
How to detect long utterances use Yamnet VAD

### ISSUE THREAD

**Issue by developerzjy** [gkonovalov/android-vad#15]
hi, I want to detect long utterances use Yamnet VAD, but I can't find the api configuration. My purpose is to detect if someone speaks in a period of time, such as within 10 seconds someone said a word. I don't care about the result of each frame, I just want a final result. Does Yamnet support this case？what should I do？

**Comment by gkonovalov** [comment]
Hi @developerzjy 

Yes, Yamnet VAD support continuous speech recognition, please see code below:
`val vad = Vad.builder()
        .setContext(applicationContext)
        .setSampleRate(SampleRate.SAMPLE_RATE_8K)
        .setFrameSize(FrameSize.FRAME_SIZE_243)
        .setMode(Mode.NORMAL)
        .setSilenceDurationMs(30)
        .setSpeechDurationMs(30)
        .build()

    vad.setContinuousClassifierListener("Speech", audioData, object : VadListener {
        override fun onResult(event: SoundCategory) {
            when (event.label) {
                "Speech" -> "Speech Detected!" + event.score
                else -> "Noise Detected!" + event.score
            }
        }
    })

    vad.close()`

**Comment by developerzjy** [comment]
I saw this code and run it, I need additional code to convert the result of each frame into a final result.
thank you
