### ISSUE TITLE
Does yamnet not need proguard?

### ISSUE THREAD

**Issue by developerzjy** [gkonovalov/android-vad#19]
I am not using any proguard for yamnet, and no problems were found in my app release version. But I'm not sure if there's a hidden problem.

**Comment by gkonovalov** [comment]
I would like to avoid using Proguard for open source library:

Application projects obfuscate the entire code base, including any referenced libraries, so they need proper configuration for the application code and for the library code. In such cases, ProGuard settings are typically handled at the application level to ensure the correct obfuscation of both the app and its dependencies.
