### ISSUE TITLE
Detects noise as a speech

### ISSUE THREAD

**Issue by mustansarsaeed** [gkonovalov/android-vad#2]
Hi, Thank you for the great library. It is detecting noise as a speech, noise can be of fan, vehicle, clap etc. it says its a speech. Can you please check what can be the issue? Configuration is as follows:

```
private val SAMPLE_RATE = 44100
    private val SAMPLE_RATE_INDEX = 4
    private val CHANNELS = 1
    private val BIT_RATE = 32000

config = VadConfig.newBuilder()
                .setSampleRate(VadConfig.SampleRate.SAMPLE_RATE_48K)
                .setFrameSize(VadConfig.FrameSize.FRAME_SIZE_480)
                .setMode(VadConfig.Mode.VERY_AGGRESSIVE)
                .setSilenceDurationMillis(500)
                .setVoiceDurationMillis(500)
                .build()
```

Your help will be appreciated.

**Comment by gkonovalov** [comment]
Hi @mustansarsaeed 
If it's pretty loud white noise then yes GMM can be mistakenly detect it as a speech.  Solution is using DNN models which can provide VAD functionality with higher accuracy. I probably in future I will add such models to this library.
