### ISSUE TITLE
How to detection audio file?

### ISSUE THREAD

**Issue by chauvansang1997** [gkonovalov/android-vad#21]
I want detetect audio file. How can I preprocess audio data?. Can you add it to example?

**Comment by gkonovalov** [comment]
This is example how you can do it:

` val vad = Vad.builder()
            .setSampleRate(SampleRate.SAMPLE_RATE_16K)
            .setFrameSize(FrameSize.FRAME_SIZE_512)
            .setMode(Mode.VERY_AGGRESSIVE)
            .build()

        val frameSize = vad.frameSize.value * 2

        val inputStream = requireContext().assets.open("test.wav")

        //Skip WAV header
        inputStream.skip(44)

        val audioData: ByteArray = inputStream.readBytes()
        val totalFrames = audioData.size / frameSize

        // Process each frame with VAD
        for (frameIndex in 0 until totalFrames) {
            val startIndex = frameIndex * frameSize
            val endIndex = startIndex + frameSize

            // Extract a frame-sized chunk
            val frameChunk = audioData.copyOfRange(startIndex, endIndex)

            // Use VAD to detect speech in the frame chunk
            val isSpeech = vad.isSpeech(frameChunk)

            // Print the result for each frame
            if (isSpeech) {
                println("Speech detected in frame $frameIndex.")
            } else {
                println("No speech detected in frame $frameIndex.")
            }
        }`
