### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by uncleTan** [gkonovalov/android-vad#22]
# CRASH STACK: 
2023-11-10 19:26:16.403 10168-11450 CrashReport                              E  SIGBUS(BUS_ADRALN)
                                                                                                    0x28fb0338f600fb
                                                                                                    #00    pc 00000000002cb968    /data/app/-EI9mCqmX1U_5phdfkkIrgA==/base.apk
                                                                                                    #01    pc 00000000002cb838    /data/app/-EI9mCqmX1U_5phdfkkIrgA==/base.apk
                                                                                                    #02    pc 00000000002c2c20    /data/app/-EI9mCqmX1U_5phdfkkIrgA==/base.apk
                                                                                                    #03    pc 0000000000124e38    /data/app/-EI9mCqmX1U_5phdfkkIrgA==/base.apk
                                                                                                    #04    pc 000000000015d8d8    /data/app/-EI9mCqmX1U_5phdfkkIrgA==/base.apk
                                                                                                    #05    pc 000000000015d610    /data/app/-EI9mCqmX1U_5phdfkkIrgA==/base.apk
                                                                                                    #06    pc 0000000000163734    /data/app/-EI9mCqmX1U_5phdfkkIrgA==/base.apk
                                                                                                    #07    pc 0000000000161bfc    /data/app/-EI9mCqmX1U_5phdfkkIrgA==/base.apk
                                                                                                    #08    pc 0000000000155ad0    /data/app/-EI9mCqmX1U_5phdfkkIrgA==/base.apk
                                                                                                    #09    pc 0000000000296e30    /data/app/-EI9mCqmX1U_5phdfkkIrgA==/base.apk
                                                                                                    #10    pc 0000000000299390    /data/app/-EI9mCqmX1U_5phdfkkIrgA==/base.apk
                                                                                                    #11    pc 0000000000070760    /data/app/-EI9mCqmX1U_5phdfkkIrgA==/base.apk
                                                                                                    #12    pc 000000000003dc40    /data/app/-EI9mCqmX1U_5phdfkkIrgA==/base.apk
                                                                                                    #13    pc 000000000003bdf8    /data/app/-EI9mCqmX1U_5phdfkkIrgA==/base.apk (Java_org_tensorflow_lite_task_audio_classifier_AudioClassifier_classifyNative+168)
                                                                                                    #14    pc 0000000000560fe0    /system/lib64/libart.so (art_quick_generic_jni_trampoline+144) [arm64-v8a::877e0c32b9c4483a1e1a5c110198885b]
                                                                                                    #15    pc 000000009cd48890    <unknown>
                                                                                                    java:
                                                                                                    org.tensorflow.lite.task.audio.classifier.AudioClassifier.classify(AudioClassifier.java:400)
                                                                                                    com.konovalov.vad.yamnet.VadYamnet.classifyAudio(VadYamnet.kt:118)
                                                                                                    com.konovalov.vad.yamnet.VadYamnet.setContinuousClassifierListener(VadYamnet.kt:134)

**Comment by gkonovalov** [comment]
Issue fixed in version 2.0.5
