### ISSUE TITLE
NoClassDefFoundError AudioUtils

### ISSUE THREAD

**Issue by BiJim** [gkonovalov/android-vad#28]
CustomActivityOnCrash: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/konovalov/vad/utils/AudioUtils;
 CustomActivityOnCrash: 	at com.konovalov.vad.webrtc.VadWebRTC.setSilenceDurationMs(VadWebRTC.kt:347)
CustomActivityOnCrash: 	at com.konovalov.vad.webrtc.VadWebRTC.<init>(VadWebRTC.kt:402)

**Comment by BiJim** [comment]
use lib  android-vad-webrtc-v2.0.6-release.aar

**Comment by gkonovalov** [comment]
Fixed: [Release 2.0.7](https://github.com/gkonovalov/android-vad/releases/tag/2.0.7)
