### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by incomingflyingbrick** [gkonovalov/android-vad#3]
Hi, is it possible to return the voice detected as an mp3 file, in the speech detected callback.  So I can upload whatever the user has said to the server.(Continuous mode)

**Comment by gkonovalov** [comment]
Purpose of this library just to provide simple functionality of fast real-time voice detector. Please feel free to add any additional encoding if you wish, currently I don't have any plans to add any other encoding besides Linear PCM.
