### ISSUE TITLE
DNN model request

### ISSUE THREAD

**Issue by kkppstudios** [gkonovalov/android-vad#6]
Hi, this library is great! I'm using it for my app and it is definitely a nice feature. You mentioned you may add a more accurate DNN model. Any timeframe in mind for this?

Thanks for your work!

**Comment by kkppstudios** [comment]
Excellent, thanks! Let me know if there's anything i can help with to contribute. 👍👍

**Comment by gkonovalov** [comment]
@kkppstudios 
Recently, a new Silero VAD DNN model has been added in the [2.0.0 release]( https://github.com/gkonovalov/android-vad/releases/tag/2.0.0).
